package com.example.lombok.controller;

import com.example.lombok.model.Product;
import com.example.lombok.service.ProductService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST Controller demonstrating Lombok's @RequiredArgsConstructor and @Slf4j.
 *
 * @RequiredArgsConstructor - Generates a constructor with required fields (final fields):
 *   public ProductController(ProductService productService) {
 *       this.productService = productService;
 *   }
 *
 * This is the MODERN WAY of dependency injection in Spring:
 * - No @Autowired needed
 * - Constructor injection (best practice)
 * - Immutable dependencies (final fields)
 * - Lombok generates the boilerplate
 *
 * @Slf4j - Generates logger for logging HTTP requests/responses
 */
@Slf4j
@RestController
@RequestMapping("/api/products")
@RequiredArgsConstructor  // Generates constructor for final fields
public class ProductController {

    // Final field - will be injected via constructor generated by @RequiredArgsConstructor
    private final ProductService productService;

    // NO MANUAL CONSTRUCTOR NEEDED! Lombok generates:
    // public ProductController(ProductService productService) {
    //     this.productService = productService;
    // }

    /**
     * GET /api/products
     * Retrieve all products
     */
    @GetMapping
    public ResponseEntity<List<Product>> getAllProducts() {
        log.info("GET /api/products - Fetching all products");
        List<Product> products = productService.getAllProducts();
        return ResponseEntity.ok(products);
    }

    /**
     * GET /api/products/{id}
     * Retrieve a product by ID
     */
    @GetMapping("/{id}")
    public ResponseEntity<Product> getProductById(@PathVariable Long id) {
        log.info("GET /api/products/{} - Fetching product", id);
        return productService.getProductById(id)
                .map(ResponseEntity::ok)
                .orElseGet(() -> {
                    log.warn("Product not found with id: {}", id);
                    return ResponseEntity.notFound().build();
                });
    }

    /**
     * POST /api/products
     * Create a new product
     */
    @PostMapping
    public ResponseEntity<Product> createProduct(@RequestBody Product product) {
        log.info("POST /api/products - Creating product: {}", product.getName());
        Product createdProduct = productService.createProduct(product);
        return ResponseEntity.status(HttpStatus.CREATED).body(createdProduct);
    }

    /**
     * PUT /api/products/{id}
     * Update an existing product
     */
    @PutMapping("/{id}")
    public ResponseEntity<Product> updateProduct(@PathVariable Long id, @RequestBody Product product) {
        log.info("PUT /api/products/{} - Updating product", id);
        return productService.updateProduct(id, product)
                .map(ResponseEntity::ok)
                .orElseGet(() -> {
                    log.warn("Cannot update - product not found with id: {}", id);
                    return ResponseEntity.notFound().build();
                });
    }

    /**
     * DELETE /api/products/{id}
     * Delete a product
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteProduct(@PathVariable Long id) {
        log.info("DELETE /api/products/{} - Deleting product", id);
        boolean deleted = productService.deleteProduct(id);

        if (deleted) {
            return ResponseEntity.noContent().build();
        } else {
            log.warn("Cannot delete - product not found with id: {}", id);
            return ResponseEntity.notFound().build();
        }
    }
}
